mostly the 5.1.22 build from oracle

diff --git a/src/VBox/Additions/linux/Makefile b/src/VBox/Additions/linux/Makefile
--- a/src/VBox/Additions/linux/Makefile
+++ b/src/VBox/Additions/linux/Makefile
@@ -27,7 +27,7 @@ else # ! KBUILD_EXTMOD
 KBUILD_VERBOSE =
 
 all:
-	@echo "*** Building 'vboxguest' module ***"
+	@echo "=== Building 'vboxguest' module ==="
 	@$(MAKE) KBUILD_VERBOSE=$(KBUILD_VERBOSE) -C vboxguest
 	@if [ -f vboxguest/vboxguest.ko ]; then \
 	    cp vboxguest/vboxguest.ko .; \
@@ -39,8 +39,8 @@ all:
 	    if [ -f vboxguest/Module.symvers ]; then \
 	        cp vboxguest/Module.symvers vboxsf; \
 	    fi; \
-	    echo "*** Building 'vboxsf' module ***"; \
-	    $(MAKE) KBUILD_VERBOSE=$(KBUILD_VERBOSE) -C vboxsf; \
+	    echo "=== Building 'vboxsf' module ==="; \
+	    $(MAKE) KBUILD_VERBOSE=$(KBUILD_VERBOSE) -C vboxsf || exit 1; \
 	    if [ -f vboxsf/vboxsf.ko ]; then \
 	        cp vboxsf/vboxsf.ko .; \
 	    else \
@@ -52,11 +52,12 @@ all:
 	    if [ -f vboxguest/Module.symvers ]; then \
 	        cp vboxguest/Module.symvers vboxvideo; \
 	    fi; \
-	    echo "*** Building 'vboxvideo' module ***"; \
-	    $(MAKE) KBUILD_VERBOSE=$(KBUILD_VERBOSE) -C vboxvideo; \
+	    echo "=== Building 'vboxvideo' module ==="; \
+	    $(MAKE) KBUILD_VERBOSE=$(KBUILD_VERBOSE) -C vboxvideo || \
+	      (echo; echo "Building of vboxvideo failed, ignoring!"; echo); \
 	    if [ -f vboxvideo/vboxvideo.ko ]; then \
 	        cp vboxvideo/vboxvideo.ko .; \
-	    else \
+	    elif [ -f vboxvideo/vboxvideo.o ]; then \
 	        cp vboxvideo/vboxvideo.o .; \
 	    fi; \
 	    echo; \
